# Generated by Django 2.1.2 on 2018-10-25 19:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('quantity', models.IntegerField(default=0, verbose_name='Quantity')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Sold Quantity')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2018, 10, 25, 19, 36, 54, 711217, tzinfo=utc), verbose_name='date added')),
            ],
        ),
    ]
