# Generated by Django 2.1.2 on 2018-10-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20181031_2337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default='2018-11-01', verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_quantity',
            field=models.IntegerField(blank=True, default=0, verbose_name='Sold Quantity'),
        ),
    ]
