# Generated by Django 2.1.2 on 2018-11-05 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0005_auto_20181105_2125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AddField(
            model_name='item',
            name='cn_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='China Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='fr_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='Franch Price'),
        ),
        migrations.AddField(
            model_name='item',
            name='sale_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='sale Price'),
        ),
    ]
