# Generated by Django 2.1.2 on 2018-11-06 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0006_auto_20181105_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default='2018-11-06', verbose_name='date added'),
        ),
    ]
