# Generated by Django 2.1.2 on 2018-11-06 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0007_auto_20181106_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, upload_to='Images', verbose_name='image'),
        ),
    ]
