# Generated by Django 2.1.2 on 2018-11-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0008_auto_20181106_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pub_date',
            field=models.DateField(blank=True, default='2018-11-11', verbose_name='date added'),
        ),
    ]
