# Generated by Django 2.1.2 on 2018-11-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20181111_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Name'),
        ),
    ]
