# Generated by Django 2.1.2 on 2018-11-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0009_auto_20181111_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
