# Generated by Django 2.1.2 on 2018-11-13 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0011_auto_20181111_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='pub_date',
        ),
    ]
