# Generated by Django 2.1.2 on 2018-11-16 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0012_remove_item_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='promo_price',
            field=models.IntegerField(blank=True, default=0, verbose_name='promo Price'),
        ),
    ]
